const propiedades = [
  {
    id: 1,
    direccion: "Bucarelli 1443",
    tipo: "Casa",
    m2: 240 + " m2",
    ambientes: 8,
    barrio: "Villa Urquiza",
    precio: "$" + 180000 + " por mes",
    operacion: "Alquiler",
    img: "./Media/bucarelli1443.jfif",
  },
  {
    id: 2,
    direccion: "Gavilan 2456",
    tipo: "Casa",
    m2: 170 + " m2",
    ambientes: 7,
    barrio: "Villa Pueyrredon",
    precio: 410000 + "USD",
    operacion: "Venta",
    img: "./Media/gavilan2456.jfif",
  },
  {
    id: 3,
    direccion: "Macedonio 510",
    tipo: "Casa",
    m2: 350 + " m2",
    ambientes: 12,
    barrio: "Saavedra",
    precio: 650000 + "USD",
    operacion: "Venta",
    img: "./Media/macedonio510.jfif",
  },
  {
    id: 4,
    direccion: "Bucarelli 2586",
    tipo: "Departamento",
    m2: 52 + " m2",
    ambientes: 2,
    barrio: "Villa Urquiza",
    precio: 130000 + "USD",
    operacion: "Venta",
    img: "./Media/bucarelli2586.jfif",
  },
  {
    id: 5,
    direccion: "Avalos 3525",
    tipo: "Departamento",
    m2: 35 + " m2",
    ambientes: 1,
    barrio: "Villa Ortuzar",
    precio: "$" + 19000 + " por mes",
    operacion: "Alquiler",
    img: "./Media/avalos3525.jfif",
  },
  {
    id: 6,
    direccion: "Juramento 1454",
    tipo: "Departamento",
    m2: 74 + " m2",
    ambientes: 3,
    barrio: "Belgrano",
    precio: "$" + 90000 + " por mes",
    operacion: "Alquiler",
    img: "./Media/juramento1454.jfif",
  },
  {
    id: 7,
    direccion: "Burela 2657",
    tipo: "Casa",
    m2: 210 + " m2",
    ambientes: 10,
    barrio: "Agronomia",
    precio: 230000 + "USD",
    operacion: "Venta",
    img: "./Media/burela.jpg",
  },
  {
    id: 8,
    direccion: "Giribone 4352",
    tipo: "Departamento",
    m2: 75 + " m2",
    ambientes: 3,
    barrio: "Villa Crespo",
    precio: 190000 + "USD",
    operacion: "Venta",
    img: "./Media/giribone4352.jpg",
  },
  {
    id: 9,
    direccion: "Treveris 2483",
    tipo: "Casa",
    m2: 185 + " m2",
    ambientes: 11,
    barrio: "Parque Chas",
    precio: 234000 + "USD",
    operacion: "Venta",
    img: "./Media/Treveris2483.jpg",
  },
  {
    id: 10,
    direccion: "Av. De Los Incas 4330",
    tipo: "Departamento",
    m2: 47 + " m2",
    ambientes: 2,
    barrio: "Villa Ortuzar",
    precio: "$" + 32000 + " por mes",
    operacion: "Alquiler",
    img: "./Media/losincas.jpg",
  },
];
